import type { Locale } from '../locales/types';
import type { FiveElementVector, FortuneResult, UserSignature } from './algorithm';
import { TAROT_DECK, type TarotCardDef, type TarotPosition } from '../data/tarotDeck';

export type WuxingResonance = 'harmony' | 'tension' | 'neutral';

export interface DailyTarotResult {
    card: TarotCardDef;
    position: TarotPosition;
    wuxingResonance: WuxingResonance;
    enhancedReading: Record<Locale, string>;
}

/** DJB2 hash — deterministic string → positive integer */
export function simpleHash(str: string): number {
    let hash = 5381;
    for (let i = 0; i < str.length; i++) {
        hash = ((hash << 5) + hash + str.charCodeAt(i)) >>> 0;
    }
    return hash;
}

// Five Elements generating cycle: wood→fire→earth→gold→water→wood
const GENERATING: Record<keyof FiveElementVector, keyof FiveElementVector> = {
    wood: 'fire',
    fire: 'earth',
    earth: 'gold',
    gold: 'water',
    water: 'wood',
};

// Five Elements controlling cycle: wood→earth→water→fire→gold→wood
const CONTROLLING: Record<keyof FiveElementVector, keyof FiveElementVector> = {
    wood: 'earth',
    earth: 'water',
    water: 'fire',
    fire: 'gold',
    gold: 'wood',
};

/**
 * Determine how the card's element relates to the user's imbalance element.
 * - harmony: card element generates or is generated by imbalance element
 * - tension: card element controls or is controlled by imbalance element
 * - neutral: same element or no direct relationship
 */
export function calculateResonance(
    cardElement: keyof FiveElementVector,
    imbalanceElement: keyof FiveElementVector,
): WuxingResonance {
    if (cardElement === imbalanceElement) return 'neutral';

    // Check generating cycle (harmony)
    if (GENERATING[cardElement] === imbalanceElement || GENERATING[imbalanceElement] === cardElement) {
        return 'harmony';
    }

    // Check controlling cycle (tension)
    if (CONTROLLING[cardElement] === imbalanceElement || CONTROLLING[imbalanceElement] === cardElement) {
        return 'tension';
    }

    return 'neutral';
}

const RESONANCE_SUFFIX: Record<WuxingResonance, Record<Locale, string>> = {
    harmony: {
        zh: '与今日五行能量共鸣，顺势而为。',
        en: 'Resonates with today\'s elemental energy — go with the flow.',
    },
    tension: {
        zh: '与今日五行能量相冲，宜审慎行事。',
        en: 'Clashes with today\'s elemental energy — proceed with caution.',
    },
    neutral: {
        zh: '与今日五行能量平和，保持内心平静。',
        en: 'In balance with today\'s elemental energy — stay centered.',
    },
};

function generateEnhancedReading(
    card: TarotCardDef,
    position: TarotPosition,
    resonance: WuxingResonance,
): Record<Locale, string> {
    const base = position === 'upright' ? card.upright : card.reversed;
    const suffix = RESONANCE_SUFFIX[resonance];
    return {
        zh: `${base.zh}。${suffix.zh}`,
        en: `${base.en}. ${suffix.en}`,
    };
}

/**
 * Draw today's tarot card. Deterministic based on date + user signature.
 * Same inputs always produce the same card for the same day.
 */
export function drawDailyTarot(
    signature: UserSignature,
    fortune: FortuneResult,
    now: Date = new Date(),
): DailyTarotResult {
    const dateKey = `${now.getFullYear()}-${now.getMonth()}-${now.getDate()}`;
    const sigKey = `${signature.gold}:${signature.wood}:${signature.water}:${signature.fire}:${signature.earth}`;
    const seed = simpleHash(`${dateKey}:${sigKey}`);

    const cardIndex = seed % 78;
    const card = TAROT_DECK[cardIndex];

    // ~33% reversed, ~67% upright
    const position: TarotPosition = (Math.floor(seed / 78) % 3 === 0) ? 'reversed' : 'upright';

    const wuxingResonance = calculateResonance(card.element, fortune.imbalanceElement);
    const enhancedReading = generateEnhancedReading(card, position, wuxingResonance);

    return { card, position, wuxingResonance, enhancedReading };
}
